[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:caddy]
command=caddy run --config /app/Caddyfile
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:monarch]
command=python /app/services/monarch/server.py
directory=/app/services/monarch
environment=PORT="8000",SERVER_URL="https://monarch.bibager.com"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:todoist]
command=python /app/services/todoist/server.py
directory=/app/services/todoist
environment=PORT="8001",SERVER_URL="https://todoist.bibager.com"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ga]
command=python /app/services/ga/server.py
directory=/app/services/ga
environment=PORT="8002"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gitlab]
command=python /app/services/gitlab/server.py
directory=/app/services/gitlab
environment=PORT="8003",SERVER_URL="https://gitlab.bibager.com"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
